# Generated by Django 5.0.7 on 2026-05-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_photo_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_radius',
            field=models.IntegerField(default=500, help_text='Poloměr check-in zóny v metrech. Výchozí: 500 m.'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Konec check-in okna. Pokud nevyplněno, použije se začátek + 4 hodiny.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Zeměpisná šířka (např. 49.1951). Povinné pro mapu a check-in.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Zeměpisná délka (např. 16.6068). Povinné pro mapu a check-in.', null=True),
        ),
    ]
