# Generated by Django 5.0.7 on 2026-05-24 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_category_event_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='survey_url',
            field=models.URLField(blank=True, default='', help_text='Volitelný dotazník. Zobrazí se uživateli po přihlášení na akci.'),
        ),
        migrations.AddField(
            model_name='event',
            name='visible_to_users',
            field=models.BooleanField(default=True, help_text='Pokud vypnuto, akce se nezobrazuje uživatelům (jen v adminu).'),
        ),
        migrations.AlterField(
            model_name='event',
            name='checkin_radius',
            field=models.IntegerField(default=500, help_text='Poloměr check-in zóny v metrech. Výchozí: 500 m.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Zeměpisná šířka (např. 49.1951). Povinné pro mapu a check-in.', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Zeměpisná délka (např. 16.6068). Povinné pro mapu a check-in.', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sheet_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='sheet_list_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
