# Generated by Django 5.0.7 on 2026-05-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0014_alter_event_unique_together_event_survey_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_to_close',
            field=models.BooleanField(default=False, help_text="Náhled pro Close: pokud zapnuto, akci uvidí role Close (a vyšší) i když je 'Viditelná pro uživatele' vypnutá."),
        ),
    ]
