# Generated by Django 5.0.7 on 2026-07-19 01:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def fix_constraint_violations(apps, schema_editor):
    """Repair rows that would violate the constraints added below.

    AddConstraint fails mid-deploy if any existing row breaks the rule, so
    rows with an obvious safe fix are repaired first (no-op on clean data).
    """
    Event = apps.get_model("leaderboard", "Event")
    EventFeedback = apps.get_model("leaderboard", "EventFeedback")
    Season = apps.get_model("leaderboard", "Season")

    # Half-set coordinate pairs: drop the lone coordinate (check-in needs both).
    Event.objects.filter(latitude__isnull=False, longitude__isnull=True).update(latitude=None)
    Event.objects.filter(latitude__isnull=True, longitude__isnull=False).update(longitude=None)

    # Non-positive check-in radius: reset to the model default.
    Event.objects.filter(checkin_radius__lt=1).update(checkin_radius=500)

    # Ratings outside 1–5: clamp to the nearest bound.
    EventFeedback.objects.filter(rating__lt=1).update(rating=1)
    EventFeedback.objects.filter(rating__gt=5).update(rating=5)

    # Multiple active seasons: keep the newest, deactivate the rest.
    active_ids = list(
        Season.objects.filter(is_active=True)
        .order_by("-start_date")
        .values_list("id", flat=True)
    )
    if len(active_ids) > 1:
        Season.objects.filter(id__in=active_ids[1:]).update(is_active=False)

    # A season whose end precedes its start has no safe auto-fix — its window
    # scopes leaderboard points, so guessing new dates could corrupt scoring.
    # Fail with a readable message instead of a cryptic constraint error.
    broken = list(
        Season.objects.filter(end_date__lte=models.F("start_date"))
        .values_list("name", flat=True)
    )
    if broken:
        raise RuntimeError(
            "Migrace zastavena: tyto sezóny mají konec před začátkem, oprav je "
            "v adminu a spusť migraci znovu: " + ", ".join(broken)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0015_event_visible_to_close'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='survey_url',
            field=models.URLField(blank=True, default='', help_text='Volitelný dotazník. Zobrazí se uživateli po přihlášení na akci.', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RunPython(fix_constraint_violations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='event_latlng_pair'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('checkin_radius__gte', 1)), name='event_checkin_radius_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventfeedback',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_1_5'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='season_single_active'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='season_end_after_start'),
        ),
    ]
