# Generated by Django 5.0.7 on 2026-07-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0019_user_number_9_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_tbd',
            field=models.BooleanField(default=False, help_text='Čas upřesníme: datum je dané, ale přesný začátek ještě ne. Místo času se zobrazí „Upřesníme“.'),
        ),
    ]
