# Generated by Django 5.0.7 on 2026-07-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0020_event_time_tbd'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='', help_text='Odkaz na WhatsApp skupinu akce. Nabídne se uživateli po přihlášení (spolu s dotazníkem).', max_length=500),
        ),
    ]
