# Generated by Django 5.0.7 on 2026-07-20 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0021_event_whatsapp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_scale',
            field=models.FloatField(default=1.0, help_text='Zvětšení/zmenšení loga při zobrazení. 1.0 = beze změny.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
