# Generated by Django 5.2.16 on 2026-10-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0028_event_date_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUpdate',
        ),
    ]
