import './PageStage.css';

/**
 * The fixed full-viewport photo behind a "poster" page, plus the grain overlay.
 *
 * Eleven pages used to carry their own copy of these rules, each drifting a
 * little (tint, grain colour, saturation, mobile un-fix). One component, three
 * tints, two grains — every photo page reads as the same material.
 *
 * image    : string — basename under /img, e.g. 'gal1'. Renders
 *            gal1-mobile.webp on phones and gal1-desktop.webp from 769px up
 *            (both are generated by `npm run images`).
 * position : string — background-position of the photo (default 'center 30%')
 * tint     : 'alive' | 'calm' | 'dim'
 *            alive — lightest; lists on a photo (leaderboard, historie)
 *            calm  — reading pages with cards (events, gallery, auth, privacy)
 *            dim   — long text or forms; the photo is mostly mood (o bodech,
 *                    event / profile forms, 404)
 * grain    : 'brown' | 'blue' | 'none' — blue only on the leaderboard family
 *
 * Mobile: styles/global.css re-anchors .page-stage / .page-grain from fixed
 * to absolute so the URL bar collapse does not jolt the photo. The page root
 * must therefore be `position:relative` (add the `has-stage` class to it).
 */
export default function PageStage({ image, position = 'center 30%', tint = 'calm', grain = 'brown' }) {
  const style = {
    '--stage-m': `url(/img/${image}-mobile.webp)`,
    '--stage-d': `url(/img/${image}-desktop.webp)`,
    '--stage-pos': position,
  };
  return (
    <>
      <div className={`page-stage page-stage--${tint}`} style={style} aria-hidden="true" />
      {grain !== 'none' && <div className={`page-grain page-grain--${grain}`} aria-hidden="true" />}
    </>
  );
}
