"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import sys
from datetime import timedelta

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MODE = os.getenv("MODE")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The key signs session cookies and password-reset tokens, so a known value
# means anyone can forge both. The dev fallback is deliberately only reachable
# when MODE != PRODUCTION; production must supply DJANGO_SECRET_KEY or refuse
# to boot (failing loudly beats silently running on a public default).
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
LAST_UPDATE = None

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "leaderboard" / "static",
]
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR / "media")

# Upload limits.
#
# These cover the *non-file* parts of a request only — Django deliberately
# exempts uploaded files from DATA_UPLOAD_MAX_MEMORY_SIZE. Per-file size,
# format and pixel-count limits live in leaderboard/image_utils.validate_upload,
# and the per-request file count is capped in the upload views.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB of form fields
# Above this, an uploaded file is spooled to a temp file instead of being held
# in RAM. It is a memory/disk trade-off, not a cap.
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
# Blunts hash-collision / parser-exhaustion POSTs with tens of thousands of keys.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
# Ceiling on files per request, enforced by the multi-image upload view.
MAX_UPLOAD_FILES_PER_REQUEST = 30


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = MODE != "PRODUCTION"

if not DEBUG and not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when MODE=PRODUCTION."
    )
if not SECRET_KEY:
    SECRET_KEY = "django-insecure-local-dev-only-not-used-in-production"

# In production, restrict to the real domain(s) via ALLOWED_HOSTS env var
# (comma-separated). A wildcard here would let an attacker set the Host header
# freely, which poisons the absolute URLs Django builds — most damagingly the
# password-reset links sent by email.
_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
elif os.getenv("RENDER_EXTERNAL_HOSTNAME"):
    # Render injects this automatically. It's a safe last resort so a deploy
    # doesn't hard-fail before ALLOWED_HOSTS is configured, but set the env var
    # explicitly — this misses any custom domain pointed at the service.
    ALLOWED_HOSTS = [os.getenv("RENDER_EXTERNAL_HOSTNAME")]
else:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS must be set when MODE=PRODUCTION "
        "(comma-separated, e.g. 'gameofyolo.com,www.gameofyolo.com')."
    )

# Number of proxies between the client and gunicorn. Production is
# Cloudflare -> Render's load balancer -> gunicorn, i.e. TWO hops, so
# X-Forwarded-For arrives as "<client>, <cloudflare-edge>".
#
# Getting this wrong is not a subtle bug: too low and the rate limiter keys on
# Cloudflare's IP, so every visitor shares one bucket and one lockout. Too high
# and it keys on a client-supplied value an attacker can forge to dodge both.
#
# Env-overridable rather than hard-coded so it can be corrected without a
# redeploy — verify the real chain at /whoami/ (superuser only) and set
# PROXY_COUNT until computed_client_ip equals your own public IP.
PROXY_COUNT = int(os.getenv("PROXY_COUNT", "1" if DEBUG else "2"))

# Only trust the SSL proxy header in production (behind a real proxy).
# In local dev with DEBUG=True, trusting this header causes Django to
# mis-detect HTTPS and mark CSRF cookies as Secure, which breaks forms over HTTP.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Whether this instance is actually reached over HTTPS. Normally true whenever
# DEBUG is off — but this repo's local .env also sets MODE=PRODUCTION, and on
# plain http://localhost the HTTPS hardening below is self-defeating: the
# redirect sends you to an https:// URL nothing serves, and Secure cookies are
# dropped by the browser, so you can never log in. Set HTTPS=0 in the local
# .env for that case; leave it unset (or 1) on Render.
HTTPS_ENABLED = not DEBUG and os.getenv("HTTPS", "1") != "0"

if HTTPS_ENABLED:
    # Render terminates TLS upstream, so this redirect decision relies on
    # SECURE_PROXY_SSL_HEADER above.
    SECURE_SSL_REDIRECT = True
    # HSTS: tell browsers to refuse plain HTTP for this domain.
    #
    # This is the ONE irreversible setting here. Once a browser has seen a long
    # max-age it honours it for that long even if the header disappears
    # tomorrow — so if HTTPS breaks, visitors cannot reach the site at all and
    # there is no way to reach out and fix their browsers.
    #
    # Default is therefore 5 minutes: real protection, but a mistake ages out
    # almost immediately. Once the deploy is confirmed healthy over HTTPS
    # (including the Cloudflare leg), raise it via the environment:
    #
    #   SECURE_HSTS_SECONDS=31536000   (1 year — the value worth ending on)
    #
    # includeSubDomains + preload are held back until the max-age is raised;
    # submitting to the preload list is effectively permanent.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "300"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS >= 86400
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS >= 31536000

    # Session/CSRF cookies must never travel over plain HTTP.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# The CSRF cookie is read by React (to echo it back in the X-CSRFToken header),
# so it cannot be HttpOnly. The session cookie can be, and is by default.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Don't let browsers second-guess Content-Type (an uploaded file sniffed as
# HTML would run as HTML), and don't leak full URLs to third-party sites.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# CSRF trusted origins for local dev + any hosted domains.
# Django 4+ requires this for POST from origins not matching the Host header.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost",
    "http://127.0.0.1",
]
_prod_origin = os.getenv("CSRF_TRUSTED_ORIGIN")
if _prod_origin:
    CSRF_TRUSTED_ORIGINS.append(_prod_origin)

# Sessions: default to expiring on browser close. The "remember me" checkbox
# on the login form overrides this per-session via session.set_expiry(...).
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'corsheaders',
    'axes',
    'leaderboard',
    'accounts',
]

# Auth lives in the React SPA; these only matter for Django's own redirects.
LOGIN_URL = '/prihlasit'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
# AxesStandaloneBackend must come first: it short-circuits authenticate() for a
# locked-out credential/IP before ModelBackend gets to verify the password.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must be last: it turns the PermissionDenied raised by the axes backend
    # into a proper lockout response.
    'axes.middleware.AxesMiddleware',
]

# ---------------------------------------------------------------------------
# django-axes: brute-force lockout on login.
#
# Why this exists alongside the DRF throttles: the throttles only cover the DRF
# auth endpoints, so /admin/login/ — a plain Django view, and the highest-value
# target on the site — had no rate limit at all. Axes hooks authenticate()
# itself, so it covers the admin and the API login in one place.
# ---------------------------------------------------------------------------
AXES_FAILURE_LIMIT = 8
# Lock out on the (IP, username) pair rather than IP alone: locking a bare IP
# would let one attacker knock every user behind a shared NAT (school/office
# wifi, mobile carriers) off the site — a denial-of-service handed to them for
# free. Per-pair still stops password spraying against a single account.
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]
# Auto-expire the lockout so a locked-out real user isn't stuck waiting for an
# admin. An attacker gets 8 tries an hour, which is useless for brute force.
AXES_COOLOFF_TIME = timedelta(hours=1)
# A successful login clears the failure count for that pair.
AXES_RESET_ON_SUCCESS = True
# Usernames are matched case-insensitively at login, so count them that way too.
AXES_USERNAME_CALLABLE = lambda request, credentials: (  # noqa: E731
    (credentials or {}).get("username") or request.POST.get("username") or ""
).strip().lower()
# Must agree with REST_FRAMEWORK["NUM_PROXIES"] — both derive from PROXY_COUNT
# so they cannot drift apart. None in DEBUG (no proxy in front locally).
AXES_IPWARE_PROXY_COUNT = None if DEBUG else PROXY_COUNT
AXES_IPWARE_META_PRECEDENCE_ORDER = ["HTTP_X_FORWARDED_FOR", "REMOTE_ADDR"]

# CORS: in dev, React on :5173 hits Django on :8000; same origin in production.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS += ["http://localhost:5173", "http://127.0.0.1:5173"]

# Native mobile app (Capacitor webview): capacitor://localhost on iOS,
# https://localhost on Android. Token-authenticated, so no CSRF entry needed.
CORS_ALLOWED_ORIGINS += [
    o.strip()
    for o in os.getenv("CORS_EXTRA_ORIGINS", "capacitor://localhost,https://localhost").split(",")
    if o.strip()
]

# Apply CORS handling to the API only.
#
# By default django-cors-headers processes every response, including /media/,
# and stamps `Vary: origin` on each one. Cloudflare only varies its cache on
# Accept-Encoding and treats other Vary values as uncacheable — so that header
# alone can keep every image at `cf-cache-status: DYNAMIC`, sending 100% of
# image traffic to the origin no matter what Cache-Control says.
#
# Safe: only XHR/fetch calls need CORS, and those all live under /api/. Images
# rendered in <img> tags (the SPA and the Capacitor webview) are not subject to
# CORS at all. This would only matter if JS read an image via fetch()/canvas.
CORS_URLS_REGEX = r"^/api/.*$"

# Version of the privacy policy currently in force, stored alongside each
# user's consent. Bump it (and the date in the React PrivacyPage) whenever the
# document changes materially — that makes it visible which users agreed to the
# old text and would need to re-confirm.
PRIVACY_POLICY_VERSION = os.getenv("PRIVACY_POLICY_VERSION", "2026-07-22")

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'mysite.drf.api_exception_handler',
    # Baseline per-IP / per-user ceiling on every endpoint. Views that need a
    # tighter limit (the auth endpoints) set their own throttle_classes, which
    # replaces this rather than adding to it.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    # Per-IP limits for the anonymous auth endpoints (see accounts/api/throttles.py).
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'register': '10/hour',
        'password_reset': '5/hour',
        # Generous: one SPA page load fans out into several requests, and
        # visitors on shared/mobile NAT share an IP. Tune down once you've
        # seen real traffic.
        'anon': '120/min',
        'user': '300/min',
    },
    # See PROXY_COUNT above — must match the real number of proxy hops, or the
    # throttle keys on the wrong address.
    'NUM_PROXIES': PROXY_COUNT,
}

# The browsable API renders every endpoint as an HTML page listing its fields
# and serializer forms. Handy locally, free API documentation for strangers in
# production — so ship JSON only there.
if not DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]

SPECTACULAR_SETTINGS = {
    'TITLE': 'Game of Life API',
    'DESCRIPTION': 'REST API for the Game of Life leaderboard platform.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Group order + descriptions for the Swagger/ReDoc sidebar. The `tags=[...]`
    # on each view (accounts/leaderboard api views) must match these names.
    'TAGS': [
        {'name': 'Auth', 'description': 'Login, registration, logout and password reset.'},
        {'name': 'Profile', 'description': 'Public profiles and editing your own account.'},
        {'name': 'Events', 'description': 'Events: listing, detail, management, RSVP, check-in and feedback.'},
        {'name': 'Leaderboard', 'description': 'Rankings, seasons and player details.'},
        {'name': 'Gallery', 'description': 'Photo gallery: uploading and liking photos.'},
        {'name': 'Home', 'description': 'Landing-page data (stats, hero carousel).'},
        {'name': 'Admin', 'description': 'Administrator-only reports.'},
    ],
}

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        # Reuse connections for up to 10 min instead of opening one per request.
        conn_max_age=int(os.getenv("CONN_MAX_AGE", "600")),
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# A 4-character minimum with no other checks made "1234" a valid password,
# which is what credential-stuffing bots try first. These four are Django's
# defaults; the messages are already translated into Czech.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# 'cs' — the UI is Czech; DRF/Django validation messages surface directly in
# the frontend forms, so they must come back localized, not in English.
LANGUAGE_CODE = 'cs'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Tests share Redis with the running dev server, so cached responses written
# by test fixtures (stats, hero, events list) would be served live for up to
# their TTL. Use an in-process cache when running under `manage.py test`.
if "test" in sys.argv:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    # Disable API throttling in the suite: throttle state lives in the cache and
    # accumulates across tests (shared client IP), so rates would cause spurious
    # 429s unrelated to the code under test. Scopes stay defined (setting them to
    # None, not removing them, avoids ImproperlyConfigured); the throttle feature
    # is covered explicitly by AuthThrottleTests via @override_settings.
    REST_FRAMEWORK = {
        **REST_FRAMEWORK,
        "DEFAULT_THROTTLE_RATES": {
            scope: None for scope in REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"]
        },
    }
    # Same reasoning for axes: failed-login attempts accumulate across tests
    # (every test client shares 127.0.0.1), so the many deliberate bad-password
    # cases in the suite would start locking each other out. The lockout
    # behaviour itself is covered by AxesLockoutTests via @override_settings.
    AXES_ENABLED = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    # CompressedStaticFilesStorage (no manifest/hashing): simpler + forgiving.
    # Avoids "Missing staticfiles manifest entry" errors if anything is out of sync.
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    # Serve the Vite build at the site root so its root-absolute references
    # (/assets/*, /gallery/*, /logos/*, /fonts/*) resolve. WHITENOISE_INDEX_FILE
    # stays off, so "/" and SPA routes fall through to the react_index view
    # (which sets the CSRF cookie).
    WHITENOISE_ROOT = os.path.join(STATIC_ROOT, 'react')

WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (password reset)
# In DEBUG: default to console backend so emails print to terminal.
# In PROD: set EMAIL_BACKEND and EMAIL_HOST_USER/PASSWORD env vars to use SMTP.
if DEBUG:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
else:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Game of Yolo <noreply@gameofyolo.cz>")


# ---------------------------------------------------------------------------
# Logging
#
# Independent of Sentry on purpose: Render captures stdout, so tracebacks stay
# readable in the dashboard even if Sentry is down, unconfigured, or over quota.
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        # Unhandled exceptions in views. Without this, a 500's traceback is
        # invisible once DEBUG is off.
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # Lockouts and repeated login failures — the audit trail for the
        # brute-force protection above.
        "axes": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# ---------------------------------------------------------------------------
# Sentry error reporting.
#
# Deliberately env-var only, with no committed fallback: unlike the frontend
# DSN (which necessarily ships inside the JS bundle and is public anyway), this
# one is never exposed to clients, so committing it would turn a private
# credential into a repo-readable one for no functional gain.
#
# Set SENTRY_DSN in Render's environment (and in djangotutorial/.env locally).
# ---------------------------------------------------------------------------
SENTRY_DSN = os.getenv("SENTRY_DSN", "")

# Never report from the test suite: several tests raise on purpose (error
# handling, the 500 path, the axes lockout), and with a DSN present in the
# local .env every run would file those synthetic failures as real issues.
if "test" in sys.argv:
    SENTRY_DSN = ""

if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("SENTRY_ENVIRONMENT", "development" if DEBUG else "production"),
        # NOT True (which is what Sentry's onboarding snippet suggests):
        # send_default_pii=True attaches the request headers, cookies, client IP
        # and the logged-in user to every event. For a Czech user base that
        # means shipping personal data to a processor on every 500 — needing a
        # legal basis and a much longer privacy-policy entry. Off, the events
        # still carry the traceback, URL and view name, which is what actually
        # helps debugging.
        send_default_pii=False,
        # Errors only. Performance tracing would burn the free-tier quota fast.
        traces_sample_rate=0,
        # Don't let a body sneak in through the request-data machinery.
        max_request_body_size="never",
    )
elif not DEBUG and "test" not in sys.argv:
    # Loud, but not fatal: missing monitoring shouldn't block a deploy.
    print(
        "WARNING: SENTRY_DSN is not set — server errors will not be reported.",
        file=sys.stderr,
    )
