# Generated by Django 5.0.7 on 2026-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
        ('leaderboard', '0013_category_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_categories',
            field=models.ManyToManyField(blank=True, related_name='fans', to='leaderboard.category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_pts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='strava',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
