# Generated by Django 5.0.7 on 2026-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_bio_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'Bez role'), ('close', 'Close (může vytvářet akce)'), ('photographer', 'Fotograf'), ('admin', 'Administrátor')], default='', help_text='Administrátor má přístup do Django adminu a vidí feedbacky. Fotograf může nahrávat oficiální fotky k akcím.', max_length=20),
        ),
    ]
