# Generated by Django 5.0.7 on 2026-07-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hide_events',
            field=models.BooleanField(default=False, help_text='Skrýt seznam akcí na profilu. ZATÍM NEVYNUCENO: hodnota se uloží, ale nic podle ní neskrývá.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_pts',
            field=models.BooleanField(default=False, help_text='Skrýt body na profilu. ZATÍM NEVYNUCENO: hodnota se uloží, ale nic podle ní neskrývá. Navíc nemá přepínač v UI.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='members_only',
            field=models.BooleanField(default=False, help_text='Profil jen pro přihlášené. ZATÍM NEVYNUCENO: hodnota se uloží, ale nic podle ní neskrývá.'),
        ),
    ]
