# Generated by Django 5.2.16 on 2026-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_hide_events_alter_profile_hide_pts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gdpr_consent_at',
            field=models.DateTimeField(blank=True, help_text='Kdy uživatel potvrdil seznámení se zásadami ochrany osobních údajů.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gdpr_consent_version',
            field=models.CharField(blank=True, default='', help_text='Verze zásad, se kterou uživatel souhlasil (např. 2026-07-22).', max_length=20),
        ),
    ]
