# Generated by Django 5.2.16 on 2026-07-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_purge_drf_auth_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hide_events',
            field=models.BooleanField(default=False, help_text='Skrýt seznam akcí na profilu.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_pts',
            field=models.BooleanField(default=False, help_text='Skrýt body a pořadí na profilu.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='members_only',
            field=models.BooleanField(default=False, help_text='Profil jen pro přihlášené (pro nepřihlášené vrací 404).'),
        ),
    ]
